version: "3"
services:
  redirect:
    build:
      dockerfile_inline: |
        FROM nginx:1.25-alpine

        ARG START_SCRIPT_PATH=/usr/local/bin/start.sh
        RUN echo "#!/bin/bash" > $$START_SCRIPT_PATH
        RUN echo "if [ -z \"\$$REDIRECT_TYPE\" ]; then" >> $$START_SCRIPT_PATH
        RUN echo "	REDIRECT_TYPE=\"permanent\"" >> $$START_SCRIPT_PATH
        RUN echo "fi" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "if [ -z \"\$$REDIRECT_TARGET\" ]; then" >> $$START_SCRIPT_PATH
        RUN echo "	echo \"Redirect target variable not set (REDIRECT_TARGET)\"" >> $$START_SCRIPT_PATH
        RUN echo "	exit 1" >> $$START_SCRIPT_PATH
        RUN echo "else" >> $$START_SCRIPT_PATH
        RUN echo "	# Add http if not set" >> $$START_SCRIPT_PATH
        RUN echo "	if ! [[ \$$REDIRECT_TARGET =~ ^https?:// ]]; then" >> $$START_SCRIPT_PATH
        RUN echo "		REDIRECT_TARGET=\"http://\$$REDIRECT_TARGET\"" >> $$START_SCRIPT_PATH
        RUN echo "	fi" >> $$START_SCRIPT_PATH
        RUN echo "fi" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "# Default to 80" >> $$START_SCRIPT_PATH
        RUN echo "LISTEN=\"80\"" >> $$START_SCRIPT_PATH
        RUN echo "# Listen to PORT variable given on Cloud Run Context" >> $$START_SCRIPT_PATH
        RUN echo "if [ ! -z \"\$$PORT\" ]; then" >> $$START_SCRIPT_PATH
        RUN echo "	LISTEN=\"\$$PORT\"" >> $$START_SCRIPT_PATH
        RUN echo "fi" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo ": \$${RETAIN_PATH:='true'}" >> $$START_SCRIPT_PATH
        RUN echo "if [ \"\$$RETAIN_PATH\" = \"true\" ]; then" >> $$START_SCRIPT_PATH
        RUN echo "	cat <<EOF > /etc/nginx/conf.d/default.conf" >> $$START_SCRIPT_PATH
        RUN echo "	server {" >> $$START_SCRIPT_PATH
        RUN echo "		listen \$${LISTEN};" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "		rewrite ^(.*)\$$ \$${REDIRECT_TARGET}\$$1 \$${REDIRECT_TYPE};" >> $$START_SCRIPT_PATH
        RUN echo "	}" >> $$START_SCRIPT_PATH
        RUN echo "EOF" >> $$START_SCRIPT_PATH
        RUN echo "else" >> $$START_SCRIPT_PATH
        RUN echo "	cat <<EOF > /etc/nginx/conf.d/default.conf" >> $$START_SCRIPT_PATH
        RUN echo "	server {" >> $$START_SCRIPT_PATH
        RUN echo "		listen \$${LISTEN};" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "		rewrite ^(.*)\$$ \$${REDIRECT_TARGET} \$${REDIRECT_TYPE};" >> $$START_SCRIPT_PATH
        RUN echo "	}" >> $$START_SCRIPT_PATH
        RUN echo "EOF" >> $$START_SCRIPT_PATH
        RUN echo "fi" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "echo \"Listening to \$$LISTEN, Redirecting HTTP requests to \$${REDIRECT_TARGET}...\"" >> $$START_SCRIPT_PATH
        RUN echo "" >> $$START_SCRIPT_PATH
        RUN echo "exec nginx -g \"daemon off;\"" >> $$START_SCRIPT_PATH

        RUN apk add --update bash \
        	&& rm -rf /var/cache/apk/* \
        	&& chmod +x /usr/local/bin/start.sh

        EXPOSE 80
    restart: always
    entrypoint:
      - "bash"
      - "start.sh"
    environment:
      - REDIRECT_TYPE=redirect
      - REDIRECT_TARGET=${REDIRECT_TARGET}
      - RETAIN_PATH=${RETAIN_PATH-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
