services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - postgres
      - docling
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data

      # ----- For Docker Volume Backup -----
      # This is the location where a snapshot of the app data
      # will be created before it is turned into a backup.
      # See `labels` to see how it's used.
      - dvb-openwebui:/tmp/dvb-snapshot
      # ------------------------------------
    expose:
      - "8080"
    environment:
      - SERVICE_FQDN_OPENWEBUI_8080

      - WEBUI_URL=${WEBUI_URL}
      - WEBUI_SECRET_KEY=${SERVICE_PASSWORD_WEBUISECRETKEY}

      # Auth (via OIDC)
      - ENABLE_SIGNUP=False
      - ENABLE_LOGIN_FORM=False
      - ENABLE_OAUTH_SIGNUP=True
      - OAUTH_CLIENT_ID=${WEBUI_OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${WEBUI_OAUTH_CLIENT_SECRET}
      - OAUTH_SCOPES=${WEBUI_OAUTH_SCOPES-openid profile email}
      - OPENID_PROVIDER_URL=${WEBUI_OPENID_PROVIDER_URL}

      # Database
      - DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-webui}

      # S3 Storage
      - STORAGE_PROVIDER=s3
      - S3_ENDPOINT_URL=${WEBUI_S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${WEBUI_S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${WEBUI_S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${WEBUI_S3_SECRET_ACCESS_KEY}

      # Docling
      - CONTENT_EXTRACTION_ENGINE=docling
      - DOCLING_SERVER_URL=http://docling:25001

      # Web Search
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=duckduckgo

      # Defaults
      - ENABLE_OLLAMA_API=False
      - DEFAULT_USER_ROLE=user
      - ENABLE_CODE_EXECUTION=False
      - ENABLE_CODE_INTERPRETER=False
      - ENABLE_TAGS_GENERATION=False
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - ENABLE_COMMUNITY_SHARING=False
      - USER_PERMISSIONS_CHAT_CONTROLS=False
      - USER_PERMISSIONS_CHAT_STT=False
      - USER_PERMISSIONS_CHAT_TTS=False
      - USER_PERMISSIONS_CHAT_CALL=False
      - USER_PERMISSIONS_FEATURES_CODE_INTERPRETER=False
      - USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS=True
      - USER_PERMISSIONS_WORKSPACE_PROMPTS_ACCESS=True
      - FILE_IMAGE_COMPRESSION_WIDTH=720
      - FILE_IMAGE_COMPRESSION_HEIGHT=720

    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1:8080"
      interval: 5s
      timeout: 30s
      retries: 10

    labels:
      # ----- For Docker Volume Backup -----
      # When the backup is triggered...
      # 1. A snapshot of the app data is created in a "temporary" directory (archive-pre)
      # 2. The backup is created based on that snapshot
      # 3. Backup is uploaded to S3
      # 4. The snapshot is deleted (archive-post)
      #
      # See https://offen.github.io/docker-volume-backup/how-tos/replace-deprecated-backup-from-snapshot.html
      - docker-volume-backup.archive-pre=cp -r /app/backend/data /tmp/dvb-snapshot/data
      - docker-volume-backup.archive-post=rm -rf /tmp/dvb-snapshot/data
      # ------------------------------------

  postgres:
    image: postgres:17-alpine
    user: postgres
    environment:
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DB:-webui}
    volumes:
      - open-webui-postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "$SERVICE_USER_POSTGRES",
          "-d",
          "$POSTGRES_DB",
        ]
      interval: 5s
      timeout: 30s
      retries: 10

  docker-volume-backup:
    # Lock to v2.43.4 (latest version as of 15-Jun-2025)
    image: offen/docker-volume-backup:v2.43.4
    depends_on:
      - open-webui
    volumes:
      # ----- For Docker Volume Backup -----
      # Creates the backup based on the "temporary" directory.
      # See `labels` of "open-webui"
      - dvb-openwebui:/backup/open-webui:ro
      # ------------------------------------
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - AWS_ENDPOINT=${DVB_S3_ENDPOINT}
      - AWS_S3_BUCKET_NAME=${DVB_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${DVB_S3_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DVB_S3_SECRET_ACCESS_KEY}

      # Backup Settings
      - BACKUP_CRON_EXPRESSION=${DVB_CRON_EXP_UTC-@daily}
      - BACKUP_RETENTION_DAYS=${DVB_RETENTION_DAYS-7}
      - BACKUP_COMPRESSION=gz
      - BACKUP_FILENAME=open-webui-dvb-%Y-%m-%dT%H-%M-%SZ.{{ .Extension }}
      - BACKUP_PRUNING_PREFIX=open-webui-dvb-

    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[/]usr/bin/backup -foreground'"]
      interval: 5s
      timeout: 30s
      retries: 10

  docling:
    image: ghcr.io/docling-project/docling-serve-cpu:v0.11.0
    environment:
      - UVICORN_PORT=25001
      - DOCLING_SERVE_ENABLE_UI=true
    ports:
      - "127.0.0.1:25001:25001"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:25001/api"
      interval: 5s
      timeout: 30s
      retries: 10

volumes:
  open-webui: {}
  dvb-openwebui: {}
