services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    expose:
      - "8080"
    environment:
      - WEBUI_SECRET_KEY=${SERVICE_PASSWORD_64_WEBUISECRETKEY}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_SCOPES=${OAUTH_SCOPES-openid profile email}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP-false}
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1:8080"
      interval: 5s
      timeout: 30s
      retries: 10

  backup:
    image: offen/docker-volume-backup:latest
    container_name: open-webui-backup
    volumes:
      - open-webui:/volume
      - ./backups/open-webui:/backup
    environment:
      - "BACKUP_FILENAME=${BACKUP_FILENAME-open-webui-backup-$(date +%Y%m%d%H%M%S).tar.gz}"
      - "BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS-7}"
      - "BACKUP_UID=0"
      - "BACKUP_GID=0"
      - "BACKUP_CRON_SCHEDULE=${BACKUP_CRON_SCHEDULE-0 0 * * *}"
      - "S3_ENDPOINT=${BACKUP_S3_ENDPOINT}"
      - "S3_ACCESS_KEY_ID=${BACKUP_S3_ACCESS_KEY_ID}"
      - "S3_SECRET_ACCESS_KEY=${BACKUP_S3_SECRET_ACCESS_KEY}"
      - "S3_BUCKET=${BACKUP_S3_BUCKET}"
    command:
      [
        "sh",
        "-c",
        'echo "${BACKUP_CRON_SCHEDULE-0 0 * * *}" | crontab - && crond -f',
      ]
    depends_on:
      - open-webui
    restart: unless-stopped

volumes:
  open-webui: {}
  open-webui-backup-data:
